# Generated by Django 5.0.6 on 2026-03-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(help_text='Paste image URL here', max_length=500)),
                ('category', models.CharField(choices=[('Nature', 'Nature & Flowers'), ('Fort', 'Historical Forts'), ('Waterfall', 'Waterfalls'), ('Spiritual', 'Spiritual & Temples')], max_length=50)),
                ('duration_hours', models.IntegerField()),
                ('price', models.IntegerField(help_text='Price in INR')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('travel_date', models.DateField()),
                ('pickup_location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
