# Generated by Django 5.0.6 on 2026-03-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image from your computer', null=True, upload_to='tour_images/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='package_type',
            field=models.CharField(choices=[('Half-Day', 'Half-Day (4-5 Hrs)'), ('Full-Day', 'Full-Day (8-10 Hrs)'), ('Custom', 'Custom Package')], default='Full-Day', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', '🚗 Sedan (Swift Dzire)'), ('SUV', '🚙 SUV (Innova)'), ('Auto', '🛺 Auto Rickshaw'), ('Tempo', '🚐 Tempo Traveller')], default='Sedan', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature & Flowers'), ('Fort', 'Historical Forts'), ('Waterfall', 'Waterfalls'), ('Spiritual', 'Spiritual & Temples')], default='Nature', max_length=50),
        ),
    ]
