# Generated by Django 6.0.3 on 2026-03-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature & Flowers'), ('Fort', 'Historical Forts'), ('Waterfall', 'Waterfalls'), ('Spiritual', 'Spiritual & Temples'), ('Student', '🎓 Student Special')], default='Nature', max_length=50),
        ),
    ]
